# Generated by Django 2.2 on 2021-04-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='feedback',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
