# Generated by Django 2.2 on 2021-04-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210430_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='feedback',
        ),
    ]
