# Generated by Django 2.2 on 2021-04-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Feedback'),
        ),
    ]
