# Generated by Django 2.2 on 2021-04-30 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210430_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
        migrations.AddField(
            model_name='productitem',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Feedback'),
        ),
    ]
